# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/InfoScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InfoScreen_Window(object):
    def setupUi(self, InfoScreen_Window):
        InfoScreen_Window.setObjectName("InfoScreen_Window")
        InfoScreen_Window.resize(748, 413)
        self.centralwidget = QtWidgets.QWidget(InfoScreen_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.groupBox)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(self.groupBox)
        self.btnEdit.setEnabled(False)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout.addWidget(self.btnEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chkUseHTTP = QtWidgets.QCheckBox(self.groupBox)
        self.chkUseHTTP.setObjectName("chkUseHTTP")
        self.horizontalLayout.addWidget(self.chkUseHTTP)
        self.btnStart = QtWidgets.QPushButton(self.groupBox)
        self.btnStart.setEnabled(False)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnMoveUp = QtWidgets.QPushButton(self.groupBox)
        self.btnMoveUp.setEnabled(False)
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.verticalLayout.addWidget(self.btnMoveUp)
        self.btnMoveDown = QtWidgets.QPushButton(self.groupBox)
        self.btnMoveDown.setEnabled(False)
        self.btnMoveDown.setObjectName("btnMoveDown")
        self.verticalLayout.addWidget(self.btnMoveDown)
        self.btnDelete = QtWidgets.QPushButton(self.groupBox)
        self.btnDelete.setEnabled(False)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        self.btnClear = QtWidgets.QPushButton(self.groupBox)
        self.btnClear.setEnabled(False)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout.addWidget(self.btnClear)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.table = QtWidgets.QTableWidget(self.groupBox)
        self.table.setShowGrid(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.table, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.lblInfoScreen = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.lblInfoScreen.setFont(font)
        self.lblInfoScreen.setObjectName("lblInfoScreen")
        self.gridLayout.addWidget(self.lblInfoScreen, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        InfoScreen_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InfoScreen_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        InfoScreen_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InfoScreen_Window)
        self.statusbar.setObjectName("statusbar")
        InfoScreen_Window.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(InfoScreen_Window)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(InfoScreen_Window)
        self.actionSave.setObjectName("actionSave")
        self.actionPreferences = QtWidgets.QAction(InfoScreen_Window)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionClose = QtWidgets.QAction(InfoScreen_Window)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtWidgets.QAction(InfoScreen_Window)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(InfoScreen_Window)
        QtCore.QMetaObject.connectSlotsByName(InfoScreen_Window)
        InfoScreen_Window.setTabOrder(self.btnAdd, self.btnEdit)
        InfoScreen_Window.setTabOrder(self.btnEdit, self.chkUseHTTP)
        InfoScreen_Window.setTabOrder(self.chkUseHTTP, self.btnStart)
        InfoScreen_Window.setTabOrder(self.btnStart, self.btnMoveUp)
        InfoScreen_Window.setTabOrder(self.btnMoveUp, self.btnMoveDown)
        InfoScreen_Window.setTabOrder(self.btnMoveDown, self.btnDelete)
        InfoScreen_Window.setTabOrder(self.btnDelete, self.btnClear)
        InfoScreen_Window.setTabOrder(self.btnClear, self.table)

    def retranslateUi(self, InfoScreen_Window):
        _translate = QtCore.QCoreApplication.translate
        InfoScreen_Window.setWindowTitle(_translate("InfoScreen_Window", "Infoscreen Setup"))
        self.groupBox.setTitle(_translate("InfoScreen_Window", "Resource Calendars"))
        self.btnAdd.setText(_translate("InfoScreen_Window", "Add"))
        self.btnEdit.setText(_translate("InfoScreen_Window", "Edit"))
        self.chkUseHTTP.setText(_translate("InfoScreen_Window", "Use SimpleHTTP"))
        self.btnStart.setText(_translate("InfoScreen_Window", "Start"))
        self.btnMoveUp.setText(_translate("InfoScreen_Window", "Move Up"))
        self.btnMoveDown.setText(_translate("InfoScreen_Window", "Move Down"))
        self.btnDelete.setText(_translate("InfoScreen_Window", "Delete"))
        self.btnClear.setText(_translate("InfoScreen_Window", "Clear"))
        self.table.setSortingEnabled(True)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("InfoScreen_Window", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("InfoScreen_Window", "Email"))
        self.lblInfoScreen.setText(_translate("InfoScreen_Window", "Infoscreen Setup"))
        self.menuFile.setTitle(_translate("InfoScreen_Window", "File"))
        self.menuHelp.setTitle(_translate("InfoScreen_Window", "Help"))
        self.actionLoad.setText(_translate("InfoScreen_Window", "Load config..."))
        self.actionSave.setText(_translate("InfoScreen_Window", "Save config..."))
        self.actionPreferences.setText(_translate("InfoScreen_Window", "Preferences"))
        self.actionClose.setText(_translate("InfoScreen_Window", "Close"))
        self.actionAbout.setText(_translate("InfoScreen_Window", "About"))

